config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root to: "static_pages#home"
  resources :screenings do
    resources :reservations, only: %i[new create] do
      collection do
        post "create_at_desk", to: "reservations#create_at_desk"
        post "create_without_registration", to: "reservations#create_without_registration"
      end
    end
  end
  resources :movies
  resources :halls
  resources :promotions, only: %i[index]
  resources :reservations, only: %i[show] do
    resources :tickets, only: %i[index]
  end
  resources :reservations, except: %i[new create] do
    patch "cancel", to: "reservations#cancel"
    patch "confirm", to: "reservations#confirm"
  end
end

app/models/hall.rb
# frozen_string_literal: true

class Hall < ApplicationRecord
  has_many :screenings
  has_many :movies, through: :screenings

  validates_associated :screenings, :movies
  validates :name, :capacity, presence: true
  validates :capacity, numericality: { greater_than: 0 }
  validates :name, uniqueness: true

  def seats
    (1..capacity).map(&:to_s)
  end
end

app/controllers/halls_controller.rb
# frozen_string_literal: true

class HallsController < ApplicationController
  before_action :set_hall, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    authorize Hall
    @halls = Hall.all
  end

  def show
    authorize Hall
  end

  def new
    authorize Hall
    @hall = Hall.new
  end

  def edit
    authorize Hall
  end

  def create
    authorize Hall
    @hall = ::Halls::Create.new(hall_params).call

    if @hall.valid?
      redirect_to hall_url(@hall), notice: I18n.t("hall.create")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize Hall
    @hall = ::Halls::Update.new(params[:id], hall_params).call

    if @hall.errors.any?
      render :edit, status: :unprocessable_entity
    else
      redirect_to hall_url(@hall), notice: I18n.t("hall.update")
    end
  end

  def destroy
    authorize Hall
    ::Halls::Delete.new(params[:id]).call

    redirect_to halls_url, notice: I18n.t("hall.destroy")
  end

  private

  def set_hall
    @hall = Hall.find(params[:id])
  end

  def hall_params
    params.require(:hall).permit(:name, :capacity)
  end
end

app/views/halls/_form.html.erb
<%= form_with(model: hall) do |form| %>
  <%= render "shared/errors" , obj: @hall %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :capacity, style: "display: block" %>
    <%= form.number_field :capacity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/halls/_hall.html.erb
<h5 class="card-title">Hall Name: </br><%= hall.name %></h5>
<h6 class="card-subtitle mb-2 text-muted">Capacity <%= hall.capacity %></h6>

app/views/halls/edit.html.erb
<h1>Editing hall</h1>

<%= render "form", hall: @hall %>

<br>

<div>
  <%= link_to "Show this hall", @hall %> |
  <%= link_to "Back to halls", halls_path %>
</div>

app/views/halls/index.html.erb
<% @halls.each do |hall| %>
  <div class="card m-3 bg-dark text-white" style="width: 30rem;">
    <div class="card-body">
      <%= render hall %>
      <p>
        <%= link_to "Show this hall", hall, class: "btn btn-outline-primary m-2" %>
      </p>
    </div>
  </div>
<% end %>
<%= link_to "New hall", new_hall_path, class: "btn btn-primary m-3"  %>

app/views/halls/new.html.erb
<h1>New hall</h1>

<%= render "form", hall: @hall %>

<br>

<div>
  <%= link_to "Back to halls", halls_path %>
</div>

app/views/halls/show.html.erb
<div class="card m-3 bg-dark text-white" style="width: 30rem;">
  <div class="card-body">
    <%= render @hall %>
    <%= link_to "Edit this hall", edit_hall_path(@hall), class: "btn btn-success m-2" %> 
    <%= link_to "Back to halls", halls_path, class: "btn btn-primary m-2" %>
    <%= button_to "Destroy this hall", @hall, method: :delete, class: "btn btn-danger m-2" %>
  </div>
</div>