config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root to: "static_pages#home"
  resources :screenings do
    resources :reservations, only: %i[new create] do
      collection do
        post "create_at_desk", to: "reservations#create_at_desk"
        post "create_without_registration", to: "reservations#create_without_registration"
      end
    end
  end
  resources :movies
  resources :halls
  resources :promotions, only: %i[index]
  resources :reservations, only: %i[show] do
    resources :tickets, only: %i[index]
  end
  resources :reservations, except: %i[new create] do
    patch "cancel", to: "reservations#cancel"
    patch "confirm", to: "reservations#confirm"
  end
end

app/models/screening.rb
# frozen_string_literal: true

class Screening < ApplicationRecord
  belongs_to :movie
  belongs_to :hall
  has_many :reservations, dependent: :destroy

  validates :start_time, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validate :used?

  def all_taken_seats
    reservations.joins(:tickets).where.not(status: :cancelled).pluck(:"tickets.seat")
  end

  def available_seats
    hall.seats - all_taken_seats.flatten
  end

  def set_end_time
    return if start_nil?

    self.end_time = start_time + movie.duration.minutes + ADS_TIME
  end

  def start_nil?
    start_time.nil?
  end

  def time_range
    start_time..end_time
  end

  def used?
    errors.add(:base, "Hall is already used for another screening") if overlaps?
  end

  private

  def overlaps?
    Screening.where(hall_id:).where.not(id:).any? do |screening|
      time_range.overlaps?(screening.time_range)
    end
  end
end

app/controllers/screenings_controller.rb
# frozen_string_literal: true

class ScreeningsController < ApplicationController
  before_action :set_screening, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show]

  def index
    authorize Screening
    @pagy, @screenings = pagy(Screening.includes(:movie, :hall))
  end

  def show
    authorize Screening
  end

  def new
    @screening = Screening.new
    authorize Screening
  end

  def edit
    authorize Screening
  end

  def create
    authorize Screening
    @screening = ::Screenings::Create.new(screening_params).call
    if @screening.errors.any?
      render :new, status: :unprocessable_entity
    else
      redirect_to screening_url(@screening), notice: I18n.t("screening.create")
    end
  end

  def update
    authorize Screening
    @screening = ::Screenings::Update.new(params[:id], screening_params).call

    if @screening.errors.any?
      render :edit, status: :unprocessable_entity
    else
      redirect_to screening_url(@screening), notice: I18n.t("screening.update")
    end
  end

  def destroy
    authorize Screening
    ::Screenings::Delete.new(params[:id]).call

    redirect_to screenings_url, notice: I18n.t("screening.destroy")
  end

  private

  def set_screening
    @screening = Screening.find(params[:id])
  end

  def screening_params
    params.require(:screening).permit(:movie_id, :hall_id, :start_time, :end_time, :price)
  end
end

app/helpers/screening_helper.rb
# frozen_string_literal: true

module ScreeningHelper
  DAYS_NUMBER = 7
  def create_date_links
    content_tag(:ul, class: "d-flex mb-3 date-links") do
      DAYS_NUMBER.times do |num|
        concat(link_to((Time.zone.today + num.days).strftime("%a %d/%m"),
                       request.params.merge(start_time: Time.zone.today + num.days), class: "mx-2 p-4 fs-5 fw-normal"))
      end
    end
  end

  def which_day?(screening)
    link_date = params[:start_time] || DateTime.now.strftime("%Y-%m-%d")
    screening.start_time.strftime("%Y-%m-%d") == link_date
  end
end

app/views/screenings/_form.html.erb
<%= form_with(model: screening) do |form| %>
  <%= render "shared/errors" , obj: @screening %>
  <div class="field">
    <%= form.label "Movie:" %>
    <%= form.select(:movie_id, Movie.all.collect {|c| [c.title, c.id ]}, { :include_blank => 'Select' }) %>
  </div>

  <div class="field">
    <%= form.label "Hall:" %>
    <%= form.select(:hall_id, Hall.all.collect {|c| [c.name, c.id ]}, { :include_blank => 'Select' }) %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/screenings/_screening.html.erb
<h5 class="card-title">Title: <%= screening.movie.title %></h5>
<h6 class="card-subtitle mb-2 text-muted">From <%= format_date(screening.start_time) %> to <%= format_date(screening.end_time) %></h6>
<p class="card-text">
  <ul>
    <li> Duration: <small><%= screening.movie.duration %> min </small></li>
    <li> Hall: <%= screening.hall.name %> </li>
    <li> Price:  <%= screening.price %> </li>
  </ul>
</p>

app/views/screenings/edit.html.erb
<h1>Editing screening</h1>

<%= render "form", screening: @screening %>

<br>

<div>
  <%= link_to "Show this screening", @screening %> |
  <%= link_to "Back to screenings", screenings_path %>
</div>

app/views/screenings/index.html.erb
<% @screenings.each do |screening| %>
  <div class="card m-3 bg-dark text-white" style="width: 30rem;">
    <div class="card-body">
      <%= render screening %>
      <p>
        <%= link_to "Show this screening", screening, class: "btn btn-outline-primary m-2"%>
      </p>
    </div>
  </div>
<% end %>
<div class="m-3"><%== pagy_bootstrap_nav(@pagy) %></div>

<%= link_to "New screening", new_screening_path, class: "btn btn-primary m-3" %>

app/views/screenings/new.html.erb
<h1>New screening</h1>

<%= render "form", screening: @screening %>

<br>

<div>
  <%= link_to "Back to screenings", screenings_path %>
</div>

app/views/screenings/show.html.erb
<div class="card m-3 bg-dark text-white" style="width: 30rem;">
  <div class="card-body">
    <%= render @screening %>
    <%= link_to "Edit this screening", edit_screening_path(@screening), class: "btn btn-success m-2" %> 
    <%= link_to "Back to screenings", screenings_path, class: "btn btn-primary m-2" %>
    <%= button_to "Destroy this screening", @screening, method: :delete, class: "btn btn-danger m-2" %>
  </div>
</div>