config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root to: "static_pages#home"
  resources :screenings do
    resources :reservations, only: %i[new create] do
      collection do
        post "create_at_desk", to: "reservations#create_at_desk"
        post "create_without_registration", to: "reservations#create_without_registration"
      end
    end
  end
  resources :movies
  resources :halls
  resources :promotions, only: %i[index]
  resources :reservations, only: %i[show] do
    resources :tickets, only: %i[index]
  end
  resources :reservations, except: %i[new create] do
    patch "cancel", to: "reservations#cancel"
    patch "confirm", to: "reservations#confirm"
  end
end

app/models/reservation.rb
# frozen_string_literal: true

class Reservation < ApplicationRecord
  enum status: { booked: 0, confirmed: 1, canceled: 2 }
  belongs_to :screening
  belongs_to :user, optional: true
  has_one :hall, through: :screening
  has_one :movie, through: :screening
  has_many :tickets, dependent: :destroy
  validates :email, presence: true
end

app/controllers/reservations_controller.rb
# frozen_string_literal: true

class ReservationsController < ApplicationController
  before_action :set_screening, only: %i[new create create_at_desk create_without_registration]
  before_action :set_reservation, only: %i[confirm cancel]
  before_action :authenticate_user!, except: %i[new create_without_registration]

  def index
    @pagy, @reservations = pagy(policy_scope(Reservation).includes(:tickets, screening: %i[movie hall]))
  end

  def show
    authorize Reservation
    @reservation = Reservation.find(params[:id])
    setup_payment_processor
  end

  def new
    authorize Reservation
    @reservation = Reservation.new
  end

  def create
    authorize Reservation
    @reservation = create_reservation(current_user.id, current_user.email, :booked)
    if @reservation.call
      redirect_to reservation_path(@reservation.reservation), notice: I18n.t("reservation.create")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def create_at_desk
    authorize Reservation
    @reservation = create_reservation(nil, "Created at desk", :confirmed)

    if @reservation.call
      redirect_to reservation_path(@reservation.reservation), notice: I18n.t("reservation.create")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def create_without_registration
    authorize Reservation
    @reservation = create_reservation(nil, params[:email], :booked)

    if @reservation.call
      redirect_to reservation_path(@reservation.reservation), notice: I18n.t("reservation.create")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def cancel
    cancelation = ::Reservations::CancelReservation.new(@reservation)
    if cancelation.call
      redirect_to reservations_path, notice: I18n.t("reservation.canceled")
    else
      redirect_back fallback_location: reservations_path, alert: I18n.t("reservation.alerts.confirmed")
    end
  end

  def confirm
    confirmation = ::Reservations::ConfirmReservation.new(@reservation)
    if confirmation.call
      redirect_to reservations_path, notice: I18n.t("reservation.confirmed")
    else
      redirect_back fallback_location: reservations_path, alert: I18n.t("reservation.alerts.canceled")
    end
  end

  private

  def set_screening
    @screening = Screening.find(params[:screening_id])
  end

  def set_reservation
    @reservation = Reservation.includes(:tickets, :screening, :hall, :movie).find(params[:reservation_id])
  end

  def create_reservation(user_id, email, status)
    ::Reservations::Create.new(
      user_id:,
      email:,
      screening_id: params[:screening_id],
      seats: params[:seats],
      status:
    )
  end

  def reservation_params
    params.require(:reservation).permit(:screening_id, :user_id, :email, :ticket_id, :status, :seats)
  end

  def setup_payment_processor
    current_user.set_payment_processor(:stripe)
    current_user.payment_processor.customer
    @checkout_session = payment_processor_checkout(current_user)
  end

  def calculate_unit_amount
    @reservation.screening.price.to_i * 100 * @reservation.tickets.count
  end

  def movie_details
    { name: @reservation.screening.movie.title, description: @reservation.screening.movie.description }
  end

  def payment_processor_checkout(current_user)
    current_user.payment_processor.checkout(mode: "payment",
                                            line_items: [
                                              { price_data: { currency: "pln",
                                                              product_data: movie_details,
                                                              unit_amount: calculate_unit_amount },
                                                quantity: 1 }
                                            ],
                                            success_url: reservation_tickets_url(@reservation),
                                            cancel_url: reservation_url(@reservation))
  end
end

app/views/reservations/_reservation.html.erb
<h5 class="card-title"> Reservation ID: <%= reservation.id %> </h5>
<h6 class="card-subtitle mb-2 text-muted">Owner: <%= reservation.email %></h6>
<div class="card-text">
  <ul>
    <li>
        <strong>Movie:</strong>
        <%= reservation.screening.movie.title %>
    </li>

    <li>
        <strong>Hall:</strong>
        <%=  reservation.screening.hall.name %> 
    </li>

    <li>
        <strong>Hall:</strong>
        <%=  format_date(reservation.screening.start_time) %> 
    </li>

    <li>
        <strong>Seat:</strong>
        <% if reservation.tickets.any? %>
          <%= reservation.tickets.map(&:seat).join(", ")  %>
        <% end %>
          
    </li>


    <li>
        <strong>Reservation status:</strong>
        <%= reservation.status %>
    </li>
  </ul>
</div>

app/views/reservations/index.html.erb
<div class="container">
  <% @reservations.each do |reservation| %>
    <div class="card m-3 bg-dark text-white" style="width: 30rem;">
      <div class="card-body">
        <%= render partial: 'reservation', locals: {reservation: reservation} %>
        <%= button_to "Cancel Reservation", reservation_cancel_path(reservation), method: :patch, class: "btn btn-danger m-2" %>
        <% if manager? %>
          <%= button_to "Confirm Reservation", reservation_confirm_path(reservation), method: :patch, class: "btn btn-success m-2" %>
        <% end %>
          <%=  link_to "Show more", reservation_path(reservation), class: "btn btn-warning m-2"%>
      </div>
    </div>
  <% end %>
  <div class="m-3"><%== pagy_bootstrap_nav(@pagy) %></div>
</div>

app/views/reservations/new.html.erb
<div class="reservation-container">    
    <h2>Title: <%= @screening.movie.title %></h2>
    <p class="fw-bold">Start Time:<%= format_date(@screening.start_time) %></p>
    <p class="fw-bold">Hall Name: <%= @screening.hall.name %></p>
  <%= form_with(url: screening_reservations_path, method: "post") do |form|%>
    <% if @reservation.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this object from being saved:</h2>
          <% @reservation.errors.each do |error| %>
            <p><%= error %></p>
          <% end %>
      </div>
    <% end %>
    <% if !current_user.present? %>
    <div>
      <%= form.label :email, style: "display: block" %>
      <%= form.text_field :email %>
    </div>
    <% end %>
    <div class="reservation-container">
      <div class="screen"></div>
      <% @screening.hall.seats.each do |seat| %>
          <div class="form-check-inline m-2">
            <%if @screening.available_seats.include?(seat)%>
              <div>
                <%= form.check_box :seats, { multiple: true, class: "form-check-input seat"}, seat, nil %>
                <div class="form-label-reservation"><%= form.label :seats, seat, class: "form-check-label"%></div>
              </div>
            <%else%>
              <div>
                <%= form.check_box :seats, { multiple: true, class: "form-check-input seat occupied", disabled: true}, seat, nil %>
                <div class="form-label-reservation"><%= form.label :seats, seat, class: "form-check-label"%></div>
              </div>
            <% end %>
          </div>
      <% end %>
    </div>
    <div class = "d-flex justify-content-center form-group ">
      <% if !current_user.present? %>
        <%= form.submit 'Book a ticket', formaction: create_without_registration_screening_reservations_path, class: "btn btn-primary m-3" %>
      <% elsif current_user.manager? %>
        <%= form.submit 'Book offline reservation', formaction: create_at_desk_screening_reservations_path, class: "btn btn-info m-3" %>
      <%else%>
          <%= form.submit 'Book a ticket', class: "btn btn-primary m-3" %>
      <%end%>
    </div>
  <% end %>
</div>

app/views/reservations/show.html.erb
<div class="container">
  <div class="card m-3 bg-dark text-white" style="width: 30rem;">
    <div class="card-body">
      <%= render partial: 'reservation', locals: {reservation: @reservation} %>
      <%= button_to "Cancel Reservation", reservation_cancel_path(@reservation), method: :patch, class: "btn btn-danger m-2" %>
      <% if manager? %>
        <%= button_to "Confirm Reservation", reservation_confirm_path(@reservation), method: :patch, class: "btn btn-success m-2" %>
      <% end %>
        <%= render partial: "pay/stripe/checkout_button", locals: {
        session: @checkout_session,
        title: "Checkout"
        } %>
    </div>
  </div>
</div>