config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root to: "static_pages#home"
  resources :screenings do
    resources :reservations, only: %i[new create] do
      collection do
        post "create_at_desk", to: "reservations#create_at_desk"
        post "create_without_registration", to: "reservations#create_without_registration"
      end
    end
  end
  resources :movies
  resources :halls
  resources :promotions, only: %i[index]
  resources :reservations, only: %i[show] do
    resources :tickets, only: %i[index]
  end
  resources :reservations, except: %i[new create] do
    patch "cancel", to: "reservations#cancel"
    patch "confirm", to: "reservations#confirm"
  end
end

app/views/layouts/_footer.html.erb
<footer class="text-white mt-auto">
  <hr>
  <!-- Copyright -->
  <div class="row text-padding-center">
    <div class="col footer-links">
      <h5> About us </h5>
      <%= link_to "Work with us", "#" %><br>
      <%= link_to "Newsletter", "#" %><br>
      <%= link_to "Contact", "#" %><br>
    </div>
    <div class="col footer-links">
      <h5> Links </h5>
      <a href="https://www.linkedin.com/in/danyflorczak/">
        <%= image_tag "linkedin.png", size: "20x20" %>
        Linkedin
      </a>
      <br>
      <a href="https://github.com/danyflorczak">
        <%= image_tag "github.png", size: "20x20" %>
        Github
      </a>
    </div>
    <div class="col footer-links">
      <h5> Info </h5>
      <%= link_to "New Movies", movies_path %><br>
      <%= link_to "Regulations", "#" %><br>
      <%= link_to "Learn More", "#" %><br>
    </div>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright: 
    <%= link_to "MonteCinema", root_path, class: "text-white" %>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_navigation.html.erb
<!-- Navbar -->
<nav class="d-flex flex-column">
  <div class="container-fluid navbar navbar-expand-lg p-5 text-padding-center" id="header-nav">
    <%= link_to "MONTE CINEMA", root_path, class: "navbar-brand"%>

    <div class="d-flex align-items-center justify-content-end collapse navbar-collapse">
      <% if current_user.present? %>
        <span class="navbar-text p-2">
          Hi <%= current_user.email %>
        </span>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-warning me-3 login-btn" %>
      <% else %>
        <%= link_to "Log In", new_user_session_path, class: "btn btn-link px-3 me-2 text-white" %>
        <%= link_to "Sign Up For Free", new_user_registration_path, class: "btn btn-warning me-3 login-btn" %>
      <% end %>
    </div>
  </div>

  <div class="container-fluid navbar navbar-expand-lg text-padding-center" id="main-menu">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "ABOUT", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "MOVIES", movies_path, class: "nav-link" %>
        </li>

        <% if current_user.present? %>
          <% if manager? %>
            <li class="nav-item">
              <%= link_to "HALLS", halls_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "SCREENINGS", screenings_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ALL RESERVATIONS", reservations_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "BOOKED RESERVATIONS", reservations_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "PROMO CODES", promotions_path, class: "nav-link" %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3"></script>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/navigation'%>
      <% if notice %>
        <p class="notice text-success"> <%=notice%> </p>
      <% end %>
      <% if alert %>
        <p class="alert text-warning"> <%=alert%> </p>
      <% end %>
      <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>